import type { CaseData, TestCase } from './types'

export const sampleCase: CaseData = {
  reference: 'NP-2291',
  yearGroup: 'Year 5 (age 9)',
  setting: 'Mainstream primary school',
  lastReview: '14 March 2026',
  nextReview: '14 March 2027',

  sections: [
    {
      id: 'A',
      letter: 'A',
      title: 'Views, interests, wishes and aspirations',
      status: 'partial',
      summary:
        'Child and parent views recorded. Aspirations captured for education but not yet for preparation for adulthood.',
      missing: [
        'Longer-term aspirations (independence, community) not yet recorded',
        'Child view gathered on one occasion only — no cross-setting comparison',
      ],
      evidenceRefs: ['EV-0007', 'EV-0011', 'EV-0018'],
    },
    {
      id: 'B',
      letter: 'B',
      title: 'Special educational needs',
      status: 'partial',
      summary:
        'Four areas of need identified from observation and setting records. One area rests on a single unverified report.',
      missing: [
        'Need B4 (sensory) supported only by one unverified report — requires professional confirmation',
        'No occupational therapy assessment available to corroborate sensory need',
      ],
      evidenceRefs: ['EV-0001', 'EV-0002', 'EV-0004', 'EV-0009', 'EV-0014'],
    },
    {
      id: 'C',
      letter: 'C',
      title: 'Health needs related to SEND',
      status: 'review',
      summary:
        'Health input referenced by school but no clinical report has been supplied to confirm health needs.',
      missing: [
        'No health professional report on file',
        'GP / paediatric input not yet requested or received',
      ],
      evidenceRefs: ['EV-0014'],
    },
    {
      id: 'D',
      letter: 'D',
      title: 'Social-care needs related to SEND',
      status: 'missing',
      summary: 'No social-care information has been supplied for this child.',
      missing: [
        'No early help or social-care assessment on file',
        'Family support needs not yet explored or recorded',
      ],
      evidenceRefs: [],
    },
    {
      id: 'E',
      letter: 'E',
      title: 'Outcomes sought',
      status: 'partial',
      summary:
        'Outcomes drafted for three of four needs. One entry is a service, not an outcome. One need has no outcome.',
      missing: [
        'Need B4 has no associated outcome',
        'Outcome OUT-03 has no baseline or measurement method',
      ],
      evidenceRefs: ['EV-0007', 'EV-0011'],
    },
    {
      id: 'F',
      letter: 'F',
      title: 'Special educational provision',
      status: 'conflict',
      summary:
        'Provision drafted for two needs. Two entries use vague, unquantified wording. One need has no provision at all.',
      missing: [
        'Need B4 (sensory) has no Section F provision',
        'Provision PR-02 is not quantified (frequency, duration and staffing missing)',
        'Provision PR-03 uses unenforceable language',
      ],
      evidenceRefs: ['EV-0001', 'EV-0002', 'EV-0009'],
    },
    {
      id: 'G',
      letter: 'G',
      title: 'Health provision',
      status: 'unavailable',
      summary:
        'Cannot be completed — the health evidence source referenced in Section C is not available.',
      missing: [
        'Health provision cannot be specified without a health report (see Section C)',
      ],
      evidenceRefs: [],
    },
    {
      id: 'H1',
      letter: 'H1',
      title: 'Social-care provision (under 18, Children Act)',
      status: 'missing',
      summary: 'No social-care provision recorded (see Section D).',
      missing: ['Depends on a social-care assessment that has not been supplied'],
      evidenceRefs: [],
    },
    {
      id: 'H2',
      letter: 'H2',
      title: 'Social-care provision (Care Act / adult)',
      status: 'missing',
      summary: 'Not applicable at present age; no adult social-care provision recorded.',
      missing: ['Revisit at preparation-for-adulthood stage'],
      evidenceRefs: [],
    },
    {
      id: 'I',
      letter: 'I',
      title: 'Educational placement',
      status: 'complete',
      summary: 'Current mainstream placement recorded with named setting.',
      missing: [],
      evidenceRefs: ['EV-0002'],
    },
    {
      id: 'J',
      letter: 'J',
      title: 'Personal budget',
      status: 'partial',
      summary: 'Personal budget not requested; family has not yet been offered the information.',
      missing: ['Record whether a personal budget has been offered and the family response'],
      evidenceRefs: [],
    },
    {
      id: 'K',
      letter: 'K',
      title: 'Advice, reports and supporting evidence',
      status: 'partial',
      summary:
        'Education and parent contributions present. Health and social-care advice missing; one report unavailable.',
      missing: [
        'Educational psychology advice not yet on file',
        'Occupational therapy advice not yet on file',
        'One referenced report (health) could not be retrieved',
      ],
      evidenceRefs: ['EV-0001', 'EV-0002', 'EV-0004', 'EV-0007', 'EV-0009', 'EV-0011'],
    },
  ],

  evidence: [
    {
      ref: 'EV-0001',
      summary:
        'Child left the classroom without warning during three literacy lessons, returning after 15–20 minutes once calm.',
      source: 'Class teacher observation log',
      contributorName: 'Recorded by class teacher',
      contributorRole: 'Class teacher',
      organisation: 'Mainstream primary school',
      dateTime: '3 Feb 2026, 09:40–11:15',
      setting: 'Classroom (literacy)',
      observation: 'direct',
      frequency: '3 times in one week',
      duration: '15–20 minutes each',
      intensity: 'Moderate — no harm, missed learning',
      crossSetting: false,
      consent: 'Consent to share with SEND team recorded',
      professionalConfirmed: true,
      label: 'direct-observation',
    },
    {
      ref: 'EV-0002',
      summary:
        'Structured observation across a full day showing withdrawal at transitions between lessons and at unstructured times.',
      source: 'SENCO structured observation',
      contributorName: 'Recorded by SENCO',
      contributorRole: 'SENCO',
      organisation: 'Mainstream primary school',
      dateTime: '10 Feb 2026, full day',
      setting: 'Whole school day',
      observation: 'direct',
      frequency: 'At most transitions observed',
      duration: 'Full day observation',
      intensity: 'Moderate to high at transitions',
      crossSetting: true,
      consent: 'Consent to share with local authority recorded',
      professionalConfirmed: true,
      label: 'confirmed',
    },
    {
      ref: 'EV-0004',
      summary:
        'Reading assessment shows attainment two years below chronological age; comprehension stronger than decoding.',
      source: 'Standardised reading assessment',
      contributorName: 'Recorded by assessment lead',
      contributorRole: 'Assessment lead',
      organisation: 'Mainstream primary school',
      dateTime: '28 Jan 2026',
      setting: 'Assessment room',
      observation: 'direct',
      frequency: 'Termly assessment',
      duration: '45 minutes',
      intensity: 'Significant gap',
      crossSetting: false,
      consent: 'Consent recorded',
      professionalConfirmed: true,
      label: 'confirmed',
    },
    {
      ref: 'EV-0007',
      summary:
        'Child said they "like drawing and want to be good at reading like my friends" and dislikes "when it gets too loud".',
      source: 'Child voice session (visual scale + short questions)',
      contributorName: 'Facilitated by teaching assistant',
      contributorRole: 'Teaching assistant',
      organisation: 'Mainstream primary school',
      dateTime: '11 Feb 2026',
      setting: 'Quiet room',
      observation: 'direct',
      frequency: 'One session',
      duration: '20 minutes',
      intensity: 'n/a',
      crossSetting: false,
      consent: 'Child agreed for views to be shared',
      professionalConfirmed: null,
      label: 'child-view',
    },
    {
      ref: 'EV-0009',
      summary:
        'Parent reports the child is exhausted and tearful after school most days, needing an hour to recover before speaking.',
      source: 'Parent contribution form',
      contributorName: 'Parent / carer',
      contributorRole: 'Parent',
      organisation: 'Home',
      dateTime: '5 Feb 2026',
      setting: 'Home',
      observation: 'reported',
      frequency: '4–5 days per week',
      duration: 'Around 1 hour recovery',
      intensity: 'High impact on home life',
      crossSetting: true,
      consent: 'Consent to share recorded',
      professionalConfirmed: null,
      label: 'parent-report',
    },
    {
      ref: 'EV-0011',
      summary:
        'Parent describes the child as calm and engaged at home when reading one-to-one, contrasting with school reports of distress.',
      source: 'Parent contribution form',
      contributorName: 'Parent / carer',
      contributorRole: 'Parent',
      organisation: 'Home',
      dateTime: '5 Feb 2026',
      setting: 'Home',
      observation: 'reported',
      frequency: 'Most evenings',
      duration: '20–30 minutes',
      intensity: 'Positive at home',
      crossSetting: true,
      consent: 'Consent to share recorded',
      professionalConfirmed: null,
      label: 'parent-report',
    },
    {
      ref: 'EV-0014',
      summary:
        'A note references a possible sensory sensitivity to noise, attributed to an unnamed source with no date.',
      source: 'Unattributed note in referral pack',
      contributorName: 'Source not identified',
      contributorRole: 'Unknown',
      organisation: 'Unknown',
      dateTime: 'Date not recorded',
      setting: 'Not stated',
      observation: 'reported',
      frequency: 'Not stated',
      duration: 'Not stated',
      intensity: 'Not stated',
      crossSetting: false,
      consent: 'Consent status unknown',
      professionalConfirmed: false,
      label: 'unverified',
    },
    {
      ref: 'EV-0018',
      summary:
        'Pattern suggestion: distress clusters around unstructured transitions and noisy environments across home and school reports.',
      source: 'NeuroPathway pattern support (requires human review)',
      contributorName: 'AI-supported pattern',
      contributorRole: 'Automated pattern support',
      organisation: 'NeuroPathway',
      dateTime: '12 Feb 2026',
      setting: 'Derived from EV-0001, EV-0002, EV-0009',
      observation: 'reported',
      frequency: 'Derived',
      duration: 'Derived',
      intensity: 'Derived',
      crossSetting: true,
      consent: 'n/a — derived from consented evidence',
      professionalConfirmed: false,
      label: 'ai-pattern',
    },
  ],

  needs: [
    {
      id: 'B1',
      title: 'Emotional regulation and response to transitions',
      domain: 'Social, emotional and mental health',
      evidenceRefs: ['EV-0001', 'EV-0002', 'EV-0009', 'EV-0018'],
      outcomeIds: ['OUT-01'],
      provisionIds: ['PR-01'],
    },
    {
      id: 'B2',
      title: 'Literacy — decoding and reading fluency',
      domain: 'Cognition and learning',
      evidenceRefs: ['EV-0004', 'EV-0011'],
      outcomeIds: ['OUT-02'],
      provisionIds: ['PR-02'],
    },
    {
      id: 'B3',
      title: 'Managing unstructured times and peer interaction',
      domain: 'Social interaction',
      evidenceRefs: ['EV-0002'],
      outcomeIds: ['OUT-03'],
      provisionIds: ['PR-03'],
    },
    {
      id: 'B4',
      title: 'Possible sensory sensitivity to noise',
      domain: 'Sensory and physical',
      evidenceRefs: ['EV-0014'],
      outcomeIds: [],
      provisionIds: [],
    },
  ],

  outcomes: [
    {
      id: 'OUT-01',
      statement:
        'By the next annual review, the child will move between lessons using an agreed transition plan, leaving the room without warning no more than once per week.',
      needId: 'B1',
      smart: {
        specific: true,
        measurable: true,
        achievable: true,
        relevant: true,
        timeBound: true,
        meaningful: true,
        aspirationLinked: true,
      },
      baseline: 'Currently leaves the room without warning 3 times per week (EV-0001).',
      intendedChange: 'Reduce unplanned exits and increase use of the agreed transition plan.',
      measurementMethod: 'Weekly transition log kept by class teacher.',
      reviewDate: '14 March 2027',
      monitorPerson: 'SENCO',
      milestones: [
        'Term 1: transition plan co-produced with child',
        'Term 2: exits reduced to twice per week',
      ],
      childViewOfSuccess: '"I can get to the next lesson without feeling worried."',
      issues: [],
    },
    {
      id: 'OUT-02',
      statement:
        'By the next annual review, the child will read age-appropriate texts with improved decoding, closing the attainment gap by at least six months of progress.',
      needId: 'B2',
      smart: {
        specific: true,
        measurable: true,
        achievable: true,
        relevant: true,
        timeBound: true,
        meaningful: true,
        aspirationLinked: true,
      },
      baseline: 'Reading two years below chronological age (EV-0004).',
      intendedChange: 'Improve decoding and narrow the attainment gap.',
      measurementMethod: 'Termly standardised reading assessment.',
      reviewDate: '14 March 2027',
      monitorPerson: 'Assessment lead',
      milestones: ['Termly reading age re-check'],
      childViewOfSuccess: '"I want to be good at reading like my friends." (EV-0007)',
      issues: [],
    },
    {
      id: 'OUT-03',
      statement: 'Three hours of pastoral support each week.',
      needId: 'B3',
      smart: {
        specific: false,
        measurable: false,
        achievable: true,
        relevant: true,
        timeBound: false,
        meaningful: false,
        aspirationLinked: false,
      },
      baseline: null,
      intendedChange: null,
      measurementMethod: null,
      reviewDate: null,
      monitorPerson: null,
      milestones: [],
      childViewOfSuccess: null,
      issues: [
        'This is a service/intervention, not an outcome — it describes provision, not the change sought for the child.',
        'No baseline recorded.',
        'No measurement method recorded.',
        'Not time-bound and not linked to what success looks like for the child.',
      ],
      isProvisionMisclassified: true,
    },
  ],

  provisions: [
    {
      id: 'PR-01',
      section: 'F',
      description:
        'A co-produced transition plan with a visual timetable and a named adult to check in at each lesson change.',
      needId: 'B1',
      outcomeId: 'OUT-01',
      responsiblePerson: 'Named teaching assistant (Key Adult)',
      expertise: 'Trained in emotion coaching and de-escalation',
      frequency: 'At every lesson transition, each school day',
      sessionDuration: '5 minutes per transition',
      totalPeriod: 'Full academic year, reviewed at annual review',
      groupType: 'individual',
      maxGroupSize: 'n/a',
      setting: 'Across the school day',
      resources: 'Visual timetable, agreed calm space',
      absenceCover: 'Named cover TA briefed on the plan',
      intendedOutcome: 'OUT-01',
      monitoring: 'Weekly transition log reviewed by SENCO',
      reviewDate: '14 March 2027',
      vagueFlags: [],
    },
    {
      id: 'PR-02',
      section: 'F',
      description:
        'The child will have access to regular small-group reading support and adult support as required.',
      needId: 'B2',
      outcomeId: 'OUT-02',
      responsiblePerson: null,
      expertise: null,
      frequency: null,
      sessionDuration: null,
      totalPeriod: null,
      groupType: 'group',
      maxGroupSize: null,
      setting: null,
      resources: null,
      absenceCover: null,
      intendedOutcome: 'OUT-02',
      monitoring: null,
      reviewDate: null,
      vagueFlags: ['access to', 'regular', 'small-group work', 'adult support', 'as required'],
    },
    {
      id: 'PR-03',
      section: 'F',
      description:
        'Staff will encourage the child and provide opportunities to join in at unstructured times when necessary.',
      needId: 'B3',
      outcomeId: 'OUT-03',
      responsiblePerson: null,
      expertise: null,
      frequency: null,
      sessionDuration: null,
      totalPeriod: null,
      groupType: null,
      maxGroupSize: null,
      setting: null,
      resources: null,
      absenceCover: null,
      intendedOutcome: null,
      monitoring: null,
      reviewDate: null,
      vagueFlags: ['staff will encourage', 'opportunities to', 'when necessary'],
    },
  ],

  delivery: [
    {
      provisionId: 'PR-01',
      plannedFrequency: 'Every lesson transition, daily',
      plannedDuration: '5 minutes',
      responsible: 'Key Adult (named TA)',
      sessionsExpected: 40,
      sessionsDelivered: 38,
      sessionsMissed: 2,
      reasonMissed: 'TA absence on 2 days',
      alternative: 'Cover TA followed the plan on 1 day; not delivered on 1 day',
      engagement: 'Child engaging well, using visual timetable independently',
      observation: 'Unplanned exits reduced from 3 to 1 per week',
      evidenceUploaded: true,
      followUp: 'Continue; review milestone at end of term',
      rag: 'green',
      accounts: [
        {
          by: 'SENCO',
          role: 'SENCO',
          note: 'Delivered as specified aside from 2 staff-absence days.',
          date: '12 March 2026',
        },
      ],
    },
    {
      provisionId: 'PR-02',
      plannedFrequency: 'Not specified in plan',
      plannedDuration: 'Not specified in plan',
      responsible: 'Not named in plan',
      sessionsExpected: 0,
      sessionsDelivered: 0,
      sessionsMissed: 0,
      reasonMissed: 'Cannot be tracked — provision not quantified',
      alternative: 'n/a',
      engagement: 'Unknown',
      observation: 'Cannot measure delivery against unquantified provision',
      evidenceUploaded: false,
      followUp: 'Rewrite PR-02 with measurable detail before delivery can be tracked',
      rag: 'grey',
    },
    {
      provisionId: 'PR-03',
      plannedFrequency: 'Not specified in plan',
      plannedDuration: 'Not specified in plan',
      responsible: 'Not named in plan',
      sessionsExpected: 12,
      sessionsDelivered: 3,
      sessionsMissed: 9,
      reasonMissed: 'No named adult allocated; support did not take place most weeks',
      alternative: 'None recorded',
      engagement: 'Child continued to spend unstructured times alone',
      observation: 'Repeatedly not delivered',
      evidenceUploaded: false,
      followUp: 'Escalate at interim review — provision not being delivered',
      rag: 'red',
      accounts: [
        {
          by: 'Parent / carer',
          role: 'Parent',
          note: 'My child says no one has helped them at breaktime this term.',
          date: '9 March 2026',
        },
        {
          by: 'SENCO',
          role: 'SENCO',
          note: 'Support offered on 3 occasions; staffing not consistently allocated.',
          date: '11 March 2026',
        },
      ],
    },
  ],

  progress: [
    {
      id: 'PM-01',
      area: 'Emotional regulation (recovery time after distress)',
      baseline: 'Up to 1 hour recovery at home (EV-0009)',
      latest: 'Around 30 minutes at home',
      trend: 'improving',
      note: 'Parent-reported improvement; corroborated by reduced school exits.',
    },
    {
      id: 'PM-02',
      area: 'Reading age',
      baseline: 'Two years below chronological age (EV-0004)',
      latest: 'Awaiting next termly assessment',
      trend: 'awaiting',
      note: 'Insufficient evidence available to judge progress yet.',
    },
    {
      id: 'PM-03',
      area: 'Engagement at unstructured times',
      baseline: 'Spends breaktimes alone',
      latest: 'No consistent change observed',
      trend: 'declining',
      note: 'Linked to non-delivery of PR-03.',
    },
    {
      id: 'PM-04',
      area: 'Attendance',
      baseline: '96% at start of year',
      latest: '95%',
      trend: 'stable',
      note: 'No significant change.',
    },
    {
      id: 'PM-05',
      area: 'Sensory regulation',
      baseline: 'Not established — need B4 unconfirmed',
      latest: 'Not measured',
      trend: 'not-measured',
      note: 'No baseline; awaiting professional assessment of possible sensory need.',
    },
    {
      id: 'PM-06',
      area: 'Child-reported wellbeing',
      baseline: 'Reported feeling "worried" at transitions',
      latest: 'Mixed — better in class, still low at breaktimes',
      trend: 'inconsistent',
      note: 'Varies by setting and time of day.',
    },
  ],

  voice: [
    {
      id: 'V-01',
      category: 'child',
      attribution: 'direct-quote',
      text: 'I like drawing and I want to be good at reading like my friends. I do not like it when it gets too loud.',
      author: 'Child (Year 5)',
      date: '11 Feb 2026',
      scale: { label: 'How school feels right now', value: 3, max: 5 },
    },
    {
      id: 'V-02',
      category: 'child',
      attribution: 'supported-comm',
      text: 'Getting to the next lesson feels worrying. A picture plan would help.',
      author: 'Child, via teaching assistant using a visual scale',
      date: '11 Feb 2026',
    },
    {
      id: 'V-03',
      category: 'parent',
      attribution: 'parent-interpretation',
      text: 'By the time they get home they are exhausted and tearful. It takes about an hour before they can talk about the day.',
      author: 'Parent / carer',
      date: '5 Feb 2026',
    },
    {
      id: 'V-04',
      category: 'professional',
      attribution: 'professional-interpretation',
      text: 'Withdrawal is most evident at unstructured transitions. A predictable routine appears to reduce distress.',
      author: 'SENCO',
      date: '10 Feb 2026',
    },
    {
      id: 'V-05',
      category: 'ai-summary',
      attribution: 'ai-summary-approved',
      text: 'Distress appears concentrated at transitions and in noisy settings, reported consistently at home and school. This is a pattern for human review, not a conclusion.',
      author: 'NeuroPathway summary — approved by SENCO',
      date: '12 Feb 2026',
    },
  ],

  safeguarding: [
    {
      id: 'SG-01',
      severity: 'serious',
      concern:
        'Parent reported that after-school distress has, on two recent occasions, included the child saying they "did not want to be here". No immediate danger reported, but the language requires a safeguarding review.',
      procedure: "School's safeguarding and child protection policy — refer to DSL same day.",
      dsl: 'Designated Safeguarding Lead (school)',
      receivedBy: 'Designated Safeguarding Lead',
      actions: [
        {
          timestamp: '6 Feb 2026, 08:30',
          action: 'Concern logged and passed to DSL',
          by: 'SENCO',
        },
        {
          timestamp: '6 Feb 2026, 09:15',
          action: 'DSL acknowledged and opened a safeguarding review',
          by: 'DSL',
        },
      ],
      acknowledged: true,
      status: 'in-progress',
      completedBy: null,
    },
  ],

  review: {
    lastReview: '14 March 2026',
    nextStatutory: '14 March 2027',
    interimDates: ['30 April 2026 (interim — PR-03 non-delivery)'],
    outcomeProgressNote:
      'OUT-01 progressing; OUT-02 awaiting assessment; OUT-03 not progressing due to provision not being delivered.',
    provisionAppropriate:
      'PR-01 appropriate and effective. PR-02 and PR-03 require rewriting to be specific and enforceable.',
    changedNeeds: 'Possible sensory need (B4) newly raised — requires professional assessment.',
    ineffectiveProvision: 'PR-03 (pastoral support) is not being delivered and is not effective.',
    undeliveredProvision: 'PR-03: 3 of 12 planned sessions delivered.',
    newEvidence: 'Parent report on after-school distress; safeguarding concern SG-01.',
    recommendedAmendments: [
      'Rewrite PR-02 with quantified frequency, duration, staffing and group size.',
      'Rewrite PR-03 with a named responsible adult and measurable delivery.',
      'Request occupational therapy assessment to confirm or discount need B4.',
      'Request health advice to complete Sections C and G.',
    ],
    childView: 'Wants a picture plan for transitions and help to read like friends.',
    parentView: 'Concerned about after-school exhaustion and lack of breaktime support.',
    professionalResponse:
      'SENCO agrees provision wording needs strengthening and further assessments are required.',
    actions: [
      {
        action: 'Rewrite PR-02 and PR-03 with measurable detail',
        responsible: 'SENCO',
        deadline: '30 April 2026',
        status: 'in-progress',
      },
      {
        action: 'Request OT assessment for possible sensory need',
        responsible: 'SENCO / local authority',
        deadline: '15 May 2026',
        status: 'agreed',
      },
      {
        action: 'Complete safeguarding review SG-01',
        responsible: 'DSL',
        deadline: '13 Feb 2026',
        status: 'in-progress',
      },
    ],
    alerts: [
      'Provision PR-03 repeatedly missed — interim review triggered',
      'New possible need (B4) raised — assessment required',
      'Open safeguarding concern (SG-01) awaiting completion by an authorised person',
    ],
  },

  audit: [
    {
      id: 'AU-01',
      dateTime: '3 Feb 2026, 11:20',
      actor: 'Class teacher',
      role: 'Class teacher',
      organisation: 'Mainstream primary school',
      action: 'Added evidence EV-0001 (classroom observation)',
      version: 'v0.1',
      changes: 'New evidence record created',
      reason: 'Recording observed behaviour',
    },
    {
      id: 'AU-02',
      dateTime: '12 Feb 2026, 14:05',
      actor: 'NeuroPathway',
      role: 'Automated pattern support',
      organisation: 'NeuroPathway',
      action: 'Generated pattern suggestion EV-0018 (labelled AI-supported pattern)',
      version: 'v0.4',
      changes: 'Draft pattern added, pending human review',
      reason: 'Highlighting a possible pattern across consented evidence',
    },
    {
      id: 'AU-03',
      dateTime: '12 Feb 2026, 15:30',
      actor: 'SENCO',
      role: 'SENCO',
      organisation: 'Mainstream primary school',
      action: 'Reviewed and approved AI summary V-05',
      version: 'v0.5',
      changes: 'Approved AI summary for inclusion in voice section',
      reason: 'Summary accurately reflects consented evidence',
    },
    {
      id: 'AU-04',
      dateTime: '14 March 2026, 10:00',
      actor: 'SENCO',
      role: 'SENCO',
      organisation: 'Mainstream primary school',
      action: 'Completed annual review record',
      version: 'v1.0',
      changes: 'Recorded review outcomes and agreed actions',
      reason: 'Statutory annual review',
    },
  ],

  aiApprovals: [
    {
      id: 'AI-01',
      content:
        'Draft summary of Need B1: "Observations across home and school describe distress concentrated at unstructured transitions."',
      approvedBy: 'SENCO',
      role: 'SENCO',
      organisation: 'Mainstream primary school',
      dateTime: '12 Feb 2026, 15:30',
      version: 'v0.5',
      changes: 'Minor wording change to avoid implying causation',
      reason: 'Accurate reflection of consented evidence',
      status: 'approved',
    },
    {
      id: 'AI-02',
      content:
        'Draft suggestion that noise sensitivity is a confirmed sensory need.',
      approvedBy: null,
      role: null,
      organisation: null,
      dateTime: null,
      version: 'draft',
      changes: 'Rejected — only one unverified source (EV-0014)',
      reason: 'Insufficient evidence; must not be presented as confirmed',
      status: 'rejected',
    },
    {
      id: 'AI-03',
      content:
        'Draft set of review questions about transitions and breaktime support for the annual review meeting.',
      approvedBy: null,
      role: null,
      organisation: null,
      dateTime: null,
      version: 'draft',
      changes: 'Awaiting human review before use',
      reason: 'Requires professional approval before being added to the record',
      status: 'draft',
    },
  ],
}

export const testCases: TestCase[] = [
  { ref: 'TC-01', profile: 'Autism-related needs, no diagnosis', complexity: 'Multiple needs', diagnosisStatus: 'No confirmed diagnosis', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 2, safeguarding: 'monitor', reviewerRoles: ['SENCO', 'Parent'], pass: true, notes: 'Needs-first language maintained throughout.' },
  { ref: 'TC-02', profile: 'ADHD-related needs', complexity: 'Multiple needs', diagnosisStatus: 'Diagnosis on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 1, safeguarding: 'none', reviewerRoles: ['SENCO', 'SEND specialist'], pass: true, notes: 'All needs linked to provision.' },
  { ref: 'TC-03', profile: 'Speech, language and communication needs', complexity: 'Single need', diagnosisStatus: 'SALT report on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 0, safeguarding: 'none', reviewerRoles: ['SALT', 'SENCO'], pass: true, notes: 'Provision quantified with SALT input.' },
  { ref: 'TC-04', profile: 'Specific learning difficulty (literacy)', complexity: 'Single need', diagnosisStatus: 'No confirmed diagnosis', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 1, safeguarding: 'none', reviewerRoles: ['SENCO', 'Parent'], pass: true, notes: 'One vague phrase flagged and rewritten.' },
  { ref: 'TC-05', profile: 'Sensory processing needs', complexity: 'Multiple needs', diagnosisStatus: 'OT assessment on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 0, safeguarding: 'none', reviewerRoles: ['OT', 'SENCO'], pass: true, notes: 'Sensory profile linked to environmental provision.' },
  { ref: 'TC-06', profile: 'SEMH — anxiety presentation', complexity: 'Multiple needs', diagnosisStatus: 'No confirmed diagnosis', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 2, safeguarding: 'active', reviewerRoles: ['SENCO', 'DSL', 'Parent'], pass: true, notes: 'Safeguarding concern surfaced and escalated correctly.' },
  { ref: 'TC-07', profile: 'Physical disability', complexity: 'Multiple needs', diagnosisStatus: 'Health report on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 0, safeguarding: 'none', reviewerRoles: ['Physiotherapist', 'SENCO'], pass: true, notes: 'Access provision quantified.' },
  { ref: 'TC-08', profile: 'Multiple and complex needs', complexity: 'Complex', diagnosisStatus: 'Multiple reports on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 2, vagueProvisionFlags: 3, safeguarding: 'monitor', reviewerRoles: ['SENCO', 'EP', 'OT', 'Parent'], pass: true, notes: 'Orphaned needs flagged for professional review.' },
  { ref: 'TC-09', profile: 'Conflicting home and school evidence', complexity: 'Multiple needs', diagnosisStatus: 'No confirmed diagnosis', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 1, safeguarding: 'none', reviewerRoles: ['SENCO', 'Parent'], pass: true, notes: 'Conflicting records preserved, not merged.' },
  { ref: 'TC-10', profile: 'Missing professional reports', complexity: 'Multiple needs', diagnosisStatus: 'Reports requested', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 1, safeguarding: 'none', reviewerRoles: ['SENCO'], pass: true, notes: 'Missing-evidence report generated; sections marked unavailable.' },
  { ref: 'TC-11', profile: 'Escalating safeguarding concern', complexity: 'Complex', diagnosisStatus: 'No confirmed diagnosis', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 0, safeguarding: 'active', reviewerRoles: ['DSL', 'SENCO', 'Social worker'], pass: true, notes: 'Urgent alert raised and audit trail preserved.' },
  { ref: 'TC-12', profile: 'Autism + PDA profile', complexity: 'Complex', diagnosisStatus: 'Diagnosis on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 2, safeguarding: 'monitor', reviewerRoles: ['EP', 'SENCO', 'Parent'], pass: true, notes: 'Provision individualised; no assumptions made.' },
  { ref: 'TC-13', profile: 'ADHD + literacy needs', complexity: 'Multiple needs', diagnosisStatus: 'Diagnosis on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 1, safeguarding: 'none', reviewerRoles: ['SENCO', 'Parent'], pass: true, notes: 'Two needs, two provision sets, both quantified.' },
  { ref: 'TC-14', profile: 'Selective mutism', complexity: 'Single need', diagnosisStatus: 'No confirmed diagnosis', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 1, safeguarding: 'none', reviewerRoles: ['SALT', 'SENCO'], pass: true, notes: 'Child voice captured via non-verbal methods.' },
  { ref: 'TC-15', profile: 'Hearing impairment', complexity: 'Single need', diagnosisStatus: 'Health report on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 0, safeguarding: 'none', reviewerRoles: ['ToD', 'SENCO'], pass: true, notes: 'Access arrangements quantified.' },
  { ref: 'TC-16', profile: 'Visual impairment', complexity: 'Single need', diagnosisStatus: 'Health report on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 0, safeguarding: 'none', reviewerRoles: ['QTVI', 'SENCO'], pass: true, notes: 'Provision specific to access needs.' },
  { ref: 'TC-17', profile: 'Developmental delay, early years', complexity: 'Multiple needs', diagnosisStatus: 'No confirmed diagnosis', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 2, safeguarding: 'none', reviewerRoles: ['EP', 'SENCO', 'Parent'], pass: true, notes: 'Needs-first framing preserved for young child.' },
  { ref: 'TC-18', profile: 'Trauma-related presentation', complexity: 'Complex', diagnosisStatus: 'No confirmed diagnosis', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 1, safeguarding: 'active', reviewerRoles: ['DSL', 'SENCO', 'Social worker'], pass: true, notes: 'Safeguarding routing worked; no diagnosis implied.' },
  { ref: 'TC-19', profile: 'Tourette syndrome', complexity: 'Multiple needs', diagnosisStatus: 'Diagnosis on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 1, safeguarding: 'none', reviewerRoles: ['SENCO', 'Parent'], pass: true, notes: 'Provision linked to functional impact.' },
  { ref: 'TC-20', profile: 'Dyspraxia (DCD)', complexity: 'Multiple needs', diagnosisStatus: 'OT assessment on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 1, safeguarding: 'none', reviewerRoles: ['OT', 'SENCO'], pass: true, notes: 'Motor-skills provision quantified.' },
  { ref: 'TC-21', profile: 'EBSA (emotionally based school avoidance)', complexity: 'Complex', diagnosisStatus: 'No confirmed diagnosis', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 2, safeguarding: 'monitor', reviewerRoles: ['SENCO', 'EP', 'Parent'], pass: true, notes: 'Attendance monitored against individual baseline.' },
  { ref: 'TC-22', profile: 'Global learning difficulty', complexity: 'Complex', diagnosisStatus: 'EP report on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 2, safeguarding: 'none', reviewerRoles: ['EP', 'SENCO', 'Parent'], pass: true, notes: 'Outcomes tied to individual baselines.' },
  { ref: 'TC-23', profile: 'Diabetes + learning needs', complexity: 'Multiple needs', diagnosisStatus: 'Health care plan on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 0, vagueProvisionFlags: 0, safeguarding: 'none', reviewerRoles: ['School nurse', 'SENCO'], pass: true, notes: 'Health and education provision separated correctly.' },
  { ref: 'TC-24', profile: 'Young person preparing for adulthood (age 16)', complexity: 'Complex', diagnosisStatus: 'Diagnosis on file', traceability: 100, investedFacts: 0, needsWithoutProvision: 1, vagueProvisionFlags: 1, safeguarding: 'none', reviewerRoles: ['SENCO', 'Careers adviser', 'Young person'], pass: true, notes: 'Aspirations for adulthood captured in the young person’s own words.' },
]
